name-template: Release v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

references: [main]

categories:
  - title: Features
    labels: [feature]
  - title: Bug Fixes
    labels: [fix, hotfix, bug, bugfix]
  - title: Other Changes
    labels: ['*']

version-resolver:
  major:
    labels: [major]
  minor:
    labels: [minor]
  patch:
    labels: [patch]
  default: patch

autolabeler:
  - label: enhancement
    branch: ['/^feature[/-].+/']
  - label: release
    branch: ['/^release[/-].+/']
  - label: hotfix
    branch: ['/^hotfix[/-].+/']
  - label: support
    branch: ['/^support[/-].+/']
  - label: chore
    branch: ['/^chore[/-].+/']
